site_name: Tutorial how to use Travis CI with C++
repo_url: https://github.com/flywire/travis_cpp_tutorial/edit/Development/docs/Tutorial.md

theme:
    name: material
    
markdown_extensions:
    - toc:
        permalink:
    - admonition
    - def_list
    - nl2br

extra_css:
    - css/extra.css
    
plugins:
    - search

nav:
    - 'Tutorial': 'Tutorial.md'
